version: "3.9"
services:
  squid:
    image: "sujithtk/squid:latest"
    hostname: squidserver
    network_mode: host
    container_name: squidproxy
    restart: always
    volumes:
      - type: volume
        source: squidlogs
        target: /var/log/squid
      - type: bind
        source: /home/itdesk/containers/squid/conf
        target: /etc/squid
      - type: bind
        source: /home/itdesk/containers/squid/squidusersdb
        target: /squidusersdb
  apache:
    image: sujithtk/apache-sarg-v1
    hostname: apache-sarg
    container_name: sarg
    restart: always
    network_mode: host
    volumes:
      - type: volume
        source: squidlogs
        target: /var/log/squid/
      - type: volume
        source: sarg-reports
        target: /var/www/html/sarg-reports/

volumes:
  squidlogs:
  sarg-reports:
